name: grocerry
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'  # Matches Flutter 3.19.0's Dart 3.3.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  http: ^1.2.0
  cloud_functions: ^4.6.0
  url_launcher: ^6.2.4
  dio: ^5.4.0
  google_maps_flutter: ^2.5.3
  geolocator: ^12.0.0
  firebase_messaging: ^14.7.10
  permission_handler: ^11.3.0
  firebase_database: ^10.4.0
  image: ^3.0.1
  firebase_storage: ^11.6.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^17.0.0
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.0.0
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  string_similarity: ^2.1.1
  tuple: ^2.0.2
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  uuid: ^4.3.3
  google_sign_in: ^6.2.1
  shimmer: ^3.0.0
  csv: ^6.0.0
  file_picker: ^8.0.0+1
  share: ^2.0.4  # Consider switching to share_plus
  uni_links: ^0.5.1  # Older, may need updating
  collection: ^1.18.0
  fluttertoast: ^8.2.5
  firebase_ml_vision: ^0.12.0+3  # Deprecated, consider alternatives
  google_mlkit_text_recognition: ^0.12.0
  google_mlkit_object_detection: ^0.12.0
  flutter_stripe: ^10.1.0
  glassmorphism: ^3.0.0
  model_viewer_plus: ^1.8.0
  country_code_picker: ^3.0.0
  background_locator: ^1.6.12
  
  geocoding: ^3.0.0
  fuzzy: ^0.5.1
  bento: ^0.0.1+alpha  # Very experimental, may not work
  lottie: ^3.1.0
  video_player: ^2.8.6
  percent_indicator: ^4.2.3
  url_strategy: ^0.2.0  # Older, consider ^0.3.0
  video_player_web: ^2.3.0
  shared_preferences: ^2.2.2
  sensors_plus: ^5.0.1
  random_string: ^2.3.1
  share_plus: ^9.0.0
  google_maps_flutter_platform_interface: ^2.5.2
  marquee: ^2.2.3
  flutter_sound: ^9.11.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  rxdart: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Already specified
  mockito: ^5.4.2  # Already specified latest

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/Comfortaa/Comfortaa-Bold.ttf
        - asset: assets/Comfortaa/Comfortaa-Light.ttf
        - asset: assets/Comfortaa/Comfortaa-Medium.ttf
        - asset: assets/Comfortaa/Comfortaa-Regular.ttf
        - asset: assets/Comfortaa/Comfortaa-SemiBold.ttf