name: grocerry
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'  # Restrict to Dart <3.0.0 for compatibility with 2.18.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages (compatible with Dart 2.18.2)
  firebase_core: ^1.24.0    # Last version before Dart 2.19.0 requirement
  firebase_auth: ^3.11.2    # Last version before Dart 2.19.0 requirement
  cloud_firestore: ^3.5.1   # Last version before Dart 2.19.0 requirement
  firebase_messaging: ^13.1.0  # Last version before Dart 2.19.0 requirement
  firebase_storage: ^10.3.11  # Last version before Dart 2.19.0 requirement
  firebase_database: ^9.1.7  # Last version before Dart 2.19.0 requirement
  cloud_functions: ^3.3.9    # Last version before Dart 2.19.0 requirement

  # UI and utility packages (compatible with Dart 2.18.2)
  flutter_svg: ^1.1.6       # Last version before Dart 2.19.0 requirement
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^0.13.5            # Compatible with Dart 2.18.2
  url_launcher: ^6.0.20    # Last version before Dart 2.19.0 requirement
  dio: ^4.0.6              # Last version before Dart 2.19.0 requirement
  google_maps_flutter: ^2.2.8  # Last version before Dart 2.19.0 requirement
  geolocator: ^9.0.2       # Last version before Dart 2.19.0 requirement
  permission_handler: ^10.2.0  # Last version before Dart 2.19.0 requirement
  image: ^3.3.0            # Last version before Dart 2.19.0 requirement
  intl: ^0.17.0            # Compatible with Dart 2.18.2
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^12.0.4  # Last version before Dart 2.19.0 requirement
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  equatable: ^2.0.5
  fl_chart: ^0.55.0
  string_similarity: ^2.1.1
  tuple: ^2.0.2
  path_provider: ^2.0.11
  image_picker: ^0.8.9      # Last version before Dart 2.19.0 requirement
  uuid: ^3.0.7             # Last version before Dart 2.19.0 requirement
  google_sign_in: ^5.4.4   # Last version before Dart 2.19.0 requirement
  shimmer: ^2.0.0          # Last version before Dart 2.19.0 requirement
  csv: ^5.0.2              # Last version before Dart 2.19.0 requirement
  file_picker: ^5.0.0     # Last version before Dart 2.19.0 requirement
  uni_links: ^0.5.1
  collection: ^1.16.0
  fluttertoast: ^8.2.2
  google_mlkit_text_recognition: ^0.11.0  # Last version before Dart 2.19.0 requirement
  google_mlkit_object_detection: ^0.11.0  # Last version before Dart 2.19.0 requirement
  flutter_stripe: ^7.0.0   # Last version before Dart 2.19.0 requirement
  glassmorphism: ^3.0.0
  model_viewer_plus: ^1.5.0  # Compatible with Dart 2.18.2
  country_code_picker: ^3.0.0  # Last version before Dart 2.19.0 requirement
  background_locator: ^1.6.12
  geocoding: ^2.0.5        # Last version before Dart 2.19.0 requirement
  fuzzy: ^0.1.0           # Last version before Dart 2.19.0 requirement
  lottie: ^1.4.3           # Last version before Dart 2.19.0 requirement
  video_player: ^2.4.10    # Last version before Dart 2.19.0 requirement
  percent_indicator: ^4.2.3
  url_strategy: ^0.2.0 
  video_player_web: ^2.0.16  # Last version before Dart 2.19.0 requirement
  shared_preferences: ^2.0.15
  sensors_plus: ^2.0.1     # Last version before Dart 2.19.0 requirement
  random_string: ^2.3.1
  share_plus: ^7.0.0       # Last version before Dart 2.19.0 requirement
  google_maps_flutter_platform_interface: ^2.2.5  # Last version before Dart 2.19.0 requirement
  marquee: ^2.2.3
  flutter_sound: ^8.5.0    # Last version before Dart 2.19.0 requirement
  flutter_map: ^3.1.0      # Last version before Dart 2.19.0 requirement
  latlong2: ^0.8.1         # Last version before Dart 2.19.0 requirement
  rxdart: ^0.27.7
  ffmpeg_kit_flutter: ^4.5.1  # Last version before Dart 2.19.0 requirement

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.3.2          # Compatible with Dart 2.18.2
  build_runner: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/3d/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/Comfortaa/Comfortaa-Bold.ttf
        - asset: assets/Comfortaa/Comfortaa-Light.ttf
        - asset: assets/Comfortaa/Comfortaa-Medium.ttf
        - asset: assets/Comfortaa/Comfortaa-Regular.ttf
        - asset: assets/Comfortaa/Comfortaa-SemiBold.ttf