name: grocerry
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'  # Matches Flutter 3.19.0's Dart 3.3.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  cloud_functions: ^5.3.4
  dio: ^5.7.0
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  firebase_messaging: ^15.2.4
  permission_handler: ^11.4.0
  firebase_database: ^11.3.4
  image: ^3.0.1
  firebase_storage: ^12.4.4
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_local_notifications: ^18.0.1
  animated_text_kit: ^4.2.2
  carousel_slider: ^5.0.0
  equatable: ^2.0.5
  fl_chart: ^0.70.2
  string_similarity: ^2.1.1
  tuple: ^2.0.2
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  google_sign_in: ^6.2.2
  shimmer: ^3.0.0
  csv: ^6.0.0
  file_picker: ^9.0.2
  share_plus: ^10.1.4  # Replace share
  collection: ^1.19.1
  fluttertoast: ^8.2.8
  google_mlkit_text_recognition: ^0.14.0  # Replace firebase_ml_vision
  google_mlkit_object_detection: ^0.14.0
  flutter_stripe: ^11.4.0
  glassmorphism: ^3.0.0
  model_viewer_plus: ^1.9.1
  country_code_picker: ^3.0.0
  background_locator: ^1.6.12 # Updated, but check web support
  geocoding: ^3.0.0
  fuzzy: ^0.5.1
  lottie: ^3.1.3
  video_player: ^2.9.3
  percent_indicator: ^4.2.3
  video_player_web: ^2.3.4
  shared_preferences: ^2.3.2
  sensors_plus: ^6.1.1
  random_string: ^2.3.1
  google_maps_flutter_platform_interface: ^2.9.2
  marquee: ^2.2.3
  flutter_sound: ^9.24.4
  flutter_map: ^8.1.0
  latlong2: ^0.9.1
  rxdart: ^0.28.0
  functions_framework: ^0.4.3+1
  # Remove flutter_ffmpeg (no web support)
  flutter_ffmpeg: ^0.4.2
  auto_size_text: ^3.0.0
  app_links: ^6.4.0

dependency_overrides:
  archive: ^4.0.4
  crypto: ^3.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Already specified
  mockito: ^5.4.2  # Already specified latest
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  webdev: ^3.7.1




flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/3d/apple.glb

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/Comfortaa/Comfortaa-Bold.ttf
        - asset: assets/Comfortaa/Comfortaa-Light.ttf
        - asset: assets/Comfortaa/Comfortaa-Medium.ttf
        - asset: assets/Comfortaa/Comfortaa-Regular.ttf
        - asset: assets/Comfortaa/Comfortaa-SemiBold.ttf